[workspace]
members = ["crates/touchstone-core", "crates/touchstone-py"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hasanzakeri/touchstone-rs"

[workspace.dependencies]
touchstone-core = { path = "crates/touchstone-core", version = "0.1.0" }
num-complex = { version = "0.4", default-features = false }
thiserror = "2"
